name: Publish Docs

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Build docs in container
      uses: ./.github/actions/container
      with:
        task: build-docs

    - name: Publish docs
      run: make docs-publish
